### ISSUE TITLE
Removed package still visible in `pdm list --graph`

### ISSUE THREAD

**Issue by pohlt** [frostming/pdm#240]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
pdm add h11
pdm remove h11
pdm list --graph
```

## Actual behavior

```
pdm-test 0.0.0 [ required: This project ]
└── h11 [ not installed ] [ required: ~=0.12 ]
```
## Expected behavior

```
pdm-test 0.0.0 [ required: This project ]
```

The package doesn't show up in the list provided by `pdm list`. I'm pretty sure I'm missing something very obvious here. 🤦‍♂️

Thanks for this great new contribution to the Python ecosystem. 👏

## Environment Information

```bash
PDM version:        1.2.0.post1               
Python Interpreter: /usr/bin/python3.8 (3.8.6)
Project Root:       /home/tom/proj/pdm_test   
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.7-1-default",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Jan 13 06:08:43 UTC 2021 (1c33a89)",
  "python_full_version": "3.8.6",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
That is because PDM, or `pkg_resources` under the hood, reads the dependencies of the current editable package from its egg-info. 
You can see it at `pdm-test.egg-info`. And the egg-info is not updated, you can simply remove that folder and re-install your project.

This however can be an enhancement with low priority, let's figure out how to improve it.
