### ISSUE TITLE
Support manage packages for global.

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#30]
From https://github.com/pdm-project/call-for-features/issues/1

1. Place a `global-project` folder under PDM app direcctory.
2. Add a command group `global` that supports following subcommands:
   - `install`
   - `sync`
   - `remove`
   - `add`
   - `update`
   - `list`

Any to add? @nasyxx

**Comment by nasyxx** [comment]
Well, and the command shows the path of the `global-project` folder.

**Comment by nasyxx** [comment]
In fact, I have thought a lot about this again.  Should we add a `run` command?

Suppose we add a global package which installs a script/executable file, should we always use `pdm run exe` to run it?  Or we should only install/link it to `$PDM.D/bin/`?

This may be another feature comes with the `global-project` that can be used instead of `pipx`.

**Comment by frostming** [comment]
My understanding is `global` commands are just like you use the global `pip` or `python`, adding dependency resolution and tracking.

`pipx` is for isolated installation, which is not "global". Although you can achieve the same thing by initialize a project, install dependencies, and link the executable at `__packages__/X.Y/bin` to `PATH`, there are still more actions than `pipx` to do. So I recommend using `pipx` directly.
